// Generated by Selenium IDE
package Pkg;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2() {
    driver.get("https://www.google.com/search?q=books&sca_esv=94cc259175ff0bb8&sxsrf=ACQVn0_Jtta2npFdXFJwkEqRiHG5fONVjw%3A1710483888399&source=hp&ei=sOnzZcbiFdvh2roPqriNmAU&iflsig=ANes7DEAAAAAZfP3wHzpkaMZjftuBS0Muf_h2wGX2w4c&ved=0ahUKEwjG-ryE0fWEAxXbsFYBHSpcA1MQ4dUDCBU&uact=5&oq=books&gs_lp=Egdnd3Mtd2l6IgVib29rczINEAAYgAQYigUYQxixAzINEAAYgAQYigUYQxixAzIQEC4YgAQYigUYQxjHARjRAzIQEC4YgAQYigUYQxjHARjRAzINEAAYgAQYigUYQxixAzINEAAYgAQYigUYQxixAzIQEAAYgAQYigUYQxixAxiDATINEAAYgAQYigUYQxixAzINEC4YgAQYigUYQxixAzINEAAYgAQYigUYQxixA0iAGlAAWIUPcAB4AJABAJgBwQKgAYkIqgEHMC40LjAuMbgBA8gBAPgBAZgCBaACrwnCAgQQIxgnwgITEC4YgAQYigUYxwEYrwEYjgUYJ8ICCxAuGIAEGLEDGIMBwgILEAAYgAQYsQMYgwHCAgsQLhiABBjHARjRA8ICBRAuGIAEwgIOEAAYgAQYigUYsQMYgwHCAggQLhiABBixA8ICChAAGIAEGIoFGEPCAggQABiABBixA8ICBRAAGIAEwgITEAAYgAQYigUYQxixAxiDARjJA8ICCxAAGIAEGIoFGJIDmAMAkgcHMC4xLjMuMaAHwEM&sclient=gws-wiz");
    driver.findElement(By.cssSelector(".eKjLze .LC20lb")).click();
  }
}
